//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShope.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int Id { get; set; }
        public string ProductArticleNumber { get; set; }
        public int IdNameProduct { get; set; }
        public int IdUnit { get; set; }
        public decimal ProductCost { get; set; }
        public decimal MaxDiscount { get; set; }
        public int IdManufacturer { get; set; }
        public int IdSupplier { get; set; }
        public int IdCategory { get; set; }
        public decimal DiscountNow { get; set; }
        public int ProductQuantityInStock { get; set; }
        public string ProductDescription { get; set; }
        public string NamePhoto { get; set; }
        public byte[] ProductPhoto { get; set; }
    
        public virtual CategoryProduct CategoryProduct { get; set; }
        public virtual ManufacturerProduct ManufacturerProduct { get; set; }
        public virtual NameProduct NameProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual SupplierProduct SupplierProduct { get; set; }
    }
}
